-- Adminer 4.6.2 MySQL dump

SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

DROP DATABASE IF EXISTS `listview`;
CREATE DATABASE `listview` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `listview`;

DROP TABLE IF EXISTS `names`;
CREATE TABLE `names` (
  `name` char(100) NOT NULL,
  `Location` varchar(100) NOT NULL,
  `Description` varchar(700) NOT NULL,
  `How to go there` varchar(500) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `names` (`name`, `Location`, `Description`, `How to go there`) VALUES
('Apiton Island',	'San Policarpo, Eastern Samar',	'Apiton Island is located at san Policarpo, Eastern Samar, a small island sorrrounded by water. The most incredible natural swimming pool wherein tourists can dive into clear waters and it provides a pleasant swimming experience. ',	'From Daniel S. Romualdez Airport, ride a jeepney to downtown area and take a van route Tacloban Borongan (Fare P250). Travel time is about 4 hours. Starting as early as 6:00AM, they have already Vans ready to leave for Borongan. Upon arriving the City of Borongan, take a tricycle going to Borongan Transport Terminal (Fare P8.00). Then ask which Bus will be going to San Policarpo Eastern Samar.  '),
('Bacayaw Resorts Cove',	'Llorente, Eastern Samar',	'A privately owned resort located at Brgy. Bacayawan, Llorente, Eastern Samar. This piece of paradise has great things to offer. An ideal place for a tropical beach holiday. Evrything composes an unforgettable picture. Aesthetically perfect premises, breath-taking nature, warm and kind-hearted people with a tradition of excellence in service, dedicated to your well-being.',	'From Daniel S. Romualdez Airport, ride a jeepney to downtown area and take a van route Tacloban Borongan (Fare P250).  Starting as early as 6:00AM, they have already Vans ready to leave for Borongan City. Vans bounded to Borongan will pass Brgy. Bacayawan. Upon arrival of Bacaywan, take a walk going to bacaywa Beach and Resort Cove.'),
('Dangkalan Pacific Beach Resort',	'Taft, Eastern Samar',	'A perfect place for camping with mini forest and park for backpackers, family, friends or lovers on leisure trip. Water sports activities and vacation accommodation awaits you on this oceanfront resort located on miles of golden fine sand facing Pacific Ocean with a beautiful sunrise view. They have 6 air-conditioned rooms and 4 standard rooms. Function Hall with 250-person capacities for seminars, weddings, baptismal and birthday parties. Mini Mart and Ice cream house.Located within the town of Taft, Eastern Samar.',	'From Daniel S. Romualdez Airport, ride a jeepney to downtown area and take a van route Tacloban Borongan (Fare P250).Travel time is about 4 hours. Starting as early as 6:00AM, they have already Vans ready to leave for Borongan City. Upon arriving the City of Borongan, take a tricycle going to Borongan Transport Terminal (Fare P8.00). Then ride a jeepney going to Taft, Eastern Samar.  '),
('Amandaraga Falls',	'Lawaan, Eastern Samar',	'Amandaraga Falls is located in Lawaan Eastern Samar Province. It was named Amandaraga because its water looked like a maiden flowing hair. The term darag means maiden. The Amandaraga Waterfalls cascades and flows into the Bulusao River, which is suitable for various water sports.',	'From Daniel S. Romualdez Airport, ride a jeepney to downtown area and take a van route Tacloban Borongan (Fare P250). Starting as early as 6:00AM, they have already Vans ready to leave for Guiuan. Travel time is around 1.5 hours. Vans bound to Guiuan will pass by the town of Lawaan and tell the driver to drop you off at the town proper. And then go to Municipal Agricultural Office and seek their assistance.'),
('Ban-awan Falls',	'Lawaan, Eastern Samar',	'Ban-awan Falls is the tallest among other falls in Lawaan, mounting to a height of 100 meters from base to peak and it servers as the water source of the municipality being located at the top of Amandaraga Falls. It has the steepest assault. The trail can be trreacherous but the scenery was truly rewarding.',	'From Daniel S. Romualdez Airport, ride a jeepney to downtown area and take a van route Tacloban Borongan (Fare P250). Starting as early as 6:00AM, they have already Vans ready to leave for Guiuan. Travel time is around 1.5 hours. Vans bound to Guiuan will pass by the town of Lawaan and tell the driver to drop you off at the town proper. And then go to Municipal Agricultural Office and seek their assistance.'),
('Zanisi Falls',	'Jipapad, Eastern Samar',	'One of the emerging tourist attraction in Jipapad, Eastern Samar Province. It was named after Fr. Angelo Severio Zanisi, an Italian missionary priest.',	'From Daniel S. Romualdez Airport, ride a jeepney to downtown area and take a van route Tacloban Borongan (Fare P250). Travel time is about 4 hours. Starting as early as 6:00AM, they have already Vans ready to leave for Borongan. Upon arriving the City of Borongan, take a tricycle going to Borongan Transport Terminal (Fare P8.00). Then ask which Bus will be going to Jipapad, Eastern Samar.  '),
('Balangiga Encounter Monument',	'Balangiga, Eastern Samar',	'Balangiga Encounter is an incident which occured on September 28, 1901. This was the date where the residents of Balangiga killed the American soldiers in an unforeseen attack using only their swords (tabak). The locals surprised the American troops at their breakfast table with an outraging attack using their bolos in retaliation for the destruction or confiscation of their food stocks, and their mission to free their fellowmen who had been held for forced labor and detained for days starving in congested conditions.',	'From Daniel S. Romualdez Airport, ride a jeepney to downtown area and take a van route Tacloban Borongan (Fare P250).Travel time is about 4 hours. Starting as early as 6:00AM, they have already Vans ready to leave for Guiuan. Vans bound to Guiuan will pass by the town of Balangiga.'),
('Magellan Landing Site',	'Guiuan, Eastern Samar',	'On March 16, 1521, Ferdinand Magellan first landed in the island of Homonhon in Eastern Samar. During the first circumnavigation of the globe, the three ships of Ferdinand Magellan passed the Marianas but even though he was out of food after crossing the Pacific Ocean, he still did not land to get some food and water. The island was still uninhabited that time, thus the common misconception that Magellan discovered the Philippines, instead of just finding it. He was seen by the boats of Rajah Culambo of Limasawa, an allly of the Rajah of Cebu, and so he was directed to Cebu on April 7.',	'From Daniel S. Romualdez Airport, ride a jeepney to downtown area and take a van route Tacloban Borongan (Fare P250). Starting as early as 6:00AM, they have already Vans ready to leave for Guiuan. Upon arrival of Guiuan Transport Terminall, ask for a boat going to Homonhon Island. Travel time is about 3 to 4 hours.'),
('US Naval Depot',	'Guiuan, Eastern Samar',	'Base of the American soldiers of WWII; commands a view of the Pacific Ocean. Base of the \'Elona Gay\' (B52 Bomber) which dropped the first atomic bomb on August 7, 1945 in Hiroshima, Japan.',	'From Daniel S. Romualdez Airport, ride a jeepney to downtown area and take a van route Tacloban Borongan (Fare P250). Starting as early as 6:00AM, they have already Vans ready to leave for Guiuan. Travel time is around 3 hours. Upon Arriving Guiuan, take a ride going to US Naval Depot.'),
('Linao Cave',	'Guiuan, Eastern Samar',	'A hidden cave in the tropical forest located just a thrilling walk away from Calicoan and Brgy. Sulangan. The name Linao Cave is derived from the word Linao or Linaw, a waray-waray term(the local dialect of Samarenos) which means \"Clear\". The locals called the cave as such because of the cold, fresh and clear waters that it houses.',	'From Daniel S. Romualdez Airport, ride a jeepney to downtown area and take a van route Tacloban Borongan (Fare P250). Starting as early as 6:00AM, they have already Vans ready to leave for Guiuan. Travel time is around 3 to 3.5 hours. At the town proper, hire a tricycle that will take you to Linao Cave.'),
('Ganap Cave',	'Borongan City, Eastern Samar',	'Ganap Cave is a 20-minute ride from the city passing through rice fields via the Maypangdan-Bayobay-Cagbonga road followed by a 5 to 10 minutes hike to the site. With beautiful spring; stalactites and stalagmites of varoius colors and sizes. The pool inside the cave is recommended for caving/ spelunking beginners.',	'From Daniel S. Romualdez Airport, ride a jeepney to downtown area and take a van route Tacloban Borongan (Fare P250).Travel time is about 4 hours. Starting as early as 6:00AM, they have already Vans ready to leave for Borongan City. Upon arriving the City of Borongan, take a tricycle going to Borongan Transport Terminal (Fare P8.00). Then ask for ride going to Brgy. Cagbonga, Borongan City.  '),
('Talubagnan Cave',	'Borongan City, Eastern Samar',	'The cave may be considered a destination for extreme caving adventure, and due to its proximity to the city proper, it is being recommended as a must see for visitors. The cave entrance is a 40-minute hike away, but time stands still once inside: where one gets to see scrutinize, and marvel at the stalactites and stalagmites hanging and jutting from the ceiling and floors, that took years to take form. The cave also has a pool where one can take a dip as a short break, before continuing on to the altar area where the most wonderful formations are on display.',	'From Daniel S. Romualdez Airport, ride a jeepney to downtown area and take a van route Tacloban Borongan (Fare P250).Travel time is about 4 hours. Starting as early as 6:00AM, they have already Vans ready to leave for Borongan City. Upon arriving the City of Borongan, take a triicycle going to brgy. bato, borongan City.'),
('Minasangay Island Ecological Park and Resort',	'Balangkayan, Eastern Samar',	'Mnasngay Island Ecological Park and Resort known for its cliff diving, scuba diving, mangroves and coral reefs is a popular gateway for the locals of the province.',	'From Daniel S. Romualdez Airport, ride a jeepney to downtown area and take a van route Tacloban Borongan (Fare P250).Travel time is about 4 hours. Starting as early as 6:00AM, they have already Vans ready to leave for Borongan City. Vans bound to Borongan will pass by the town of Balangkayan. Upon arrival to Balangkayan, take a tricycle going to Minasangay Island.'),
('Jagnaya Beach',	'Salcedo, Eastern Samar',	'A natural saltwater pool extends from the cave, and during high tide, it connects to the ocean. This is specially great for swimmers who wants to enjoy the water but get some shade. Jagnaya is not commercialized so you cannot expect basic facilities and stores around.',	'From Daniel S. Romualdez Airport ride a jeepney to downtown arrea and take a Van route Tacloban to Guiuan and tell the driver to drop you off at the waiting shed in Salcedo going to Jagnaya. Waiting shed is on the left side of the national Highway. Estimated Travel time is 2 hours and 30 minutes to 3 hours.'),
('Liliputan Rocky Beach Resort',	'San Julian, Eastern Samar',	'Liliputan literally means where one turns around a point, from the root word liput meaing to turn around a point. It is famous for its amazing rock formations and natural pool that is equivalent to a 6 Olympic size swimming pool.',	'From Daniel S. Romualdez Airport, ride a jeepney to downtown area and take a van route Tacloban Borongan (Fare P250).  Starting as early as 6:00AM, they have already Vans ready to leave for Borongan City.  Upon arrival to the City, take a ride in a tricycle going to Borongan Transport Terminal (Fare P8.00). Then ask for a ride to San Julian, Eastern Samar (Fare P35.00).'),
('Canhugas nature Park',	'Hernani, Eastern Samar',	'Canhugas comes from a root word \'hugas\' which means to wash. During the ancient times, fisherman were observed to be visiting the site to wash their caught fishes before going home. Today, Canhugas Nature Park is a good place for those men and women who wishes to move on before 2019 starts by letting the pain be washed through the appreciation of the nature\'s work of art.',	'From Daniel S. Romualdez Airport, ride a jeepney to downtown area and take a van route Tacloban Borongan (Fare P250). Travel time is about 4 hours. Starting as early as 6:00AM, they have already Vans ready to leave for Borongan City. Vans bound to Borongan will pass by the town of Hernani. Upon arrival to Hernani, Canhugas Nature Park is just a walking distance, just ask the community and they will accompany you.'),
('Tingson Falls',	'General MacArthur, Eastern Samar',	'Tingson Falls is a perfect get-away for those who wish to take a break from the daily hustle of life. Allows the clear water to refresh your tired body and the sound of rushing waterfall sooth your senses and ease your mind.',	'From Daniel S. Romualdez Airport, ride a jeepney to downtown area and take a van route Tacloban Borongan (Fare P200). Starting as early as 6:00AM, they have already Vans ready to leave for Borongan. Vans bound to Borongan will pass by the town of General MacArthur. Travel time is around 3 hours.'),
('Pangi Falls',	'Borongan City, Eastern Samar',	'A physical demanding 3 to 4 hours ascending hike in the San Gabriel Mountains, along river crossings to reach the site; but worth every aching muscle once the 80 foot Pangi Falls is in sight. This path leads one to the top of the falls. The descent to the pool at the foot of the falls may be a little tricky and requires one to be extra careful; there are no stairs to use in the descent but foot trails and roots and trunks of young trees for support.',	'From Daniel S. Romualdez Airport, ride a jeepney to downtown area and take a van route Tacloban Borongan (Fare P250).Travel time is about 4 hours. Starting as early as 6:00AM, they have already Vans ready to leave for Borongan City. Upon arriving the City of Borongan, take a tricycle going to Borongan Transport Terminal (Fare P8.00). Then ride a tricycle going to Brgy. San Gabriel, Borongan City.'),
('Eugenio S. Daza Monument',	'Borongan City, Eastern Samar',	'A statue built to remind the heroic act done by Maj. Eugenio S. Daza, a local hero. During the Philippine-American war in 1899. Daza was appointed Commander of the revolutionary forces in Eastern Samar. Was one of the leaders in the Balangiga attack on September 28, 1901, where Filipinos succeeded against the American forces, in Eastern Samar.',	'From Daniel S. Romualdez Airport, ride a jeepney to downtown area and take a van route Tacloban Borongan (Fare P250).Travel time is about 4 hours. Starting as early as 6:00AM, they have already Vans ready to leave for Borongan City. Upon arriving the City of Borongan, take a tricycle going to Eugenioi S. Daza Monument in Rawis Rd. Borongan City(Fare P8.00).'),
('Nahulopan Cave',	'Taft, Eastern Samar',	'Nahulopan Cave is a subterranean beauty withan explored cave length over 1,300 meters (1.3 km) boosting a series of underground swimming pool, streams, magnificient rock formation and mini waterfalls. ',	'From Daniel S. Romualdez Airport, ride a jeepney to downtown area and take a van route Tacloban Borongan (Fare P250).Travel time is about 4 hours. Starting as early as 6:00AM, they have already Vans ready to leave for Borongan City. Upon arriving the City of Borongan, take a tricycle going to Borongan Transport Terminal (Fare P8.00). Then ride a jeepney going to Taft, Eastern Samar.  '),
('Linal-an Cave',	'Borongan City, Eastern Samar',	'Accessible by trekking (one hour 45 minutes) or by banca (canoe one hour 15 minutes). How deep this cave is remains to be discovered; however, it was the coldest cave pool in all the pools in the area. The storyteller prefers swimming alongside the canoe on the way home and having fun while playing in the rapids.',	'From Daniel S. Romualdez Airport, ride a jeepney to downtown area and take a van route Tacloban Borongan (Fare P250). Travel time is about 4 hours. Starting as early as 6:00AM, they have already Vans ready to leave for Borongan. Upon arriving the City of Borongan, take a tricycle going to Brgy. Can-abong, Borongan City. ');

-- 2018-03-01 23:01:00
